/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as CatalogoCategoriaRouteImport } from './routes/catalogo.$categoria'
import { Route as ColeccionIdRouteImport } from './routes/coleccion.$id'
import { Route as PeliculaIdRouteImport } from './routes/pelicula.$id'
import { Route as PersonaIdRouteImport } from './routes/persona.$id'
import { Route as SerieIdRouteImport } from './routes/serie.$id'
import { Route as SerieIdTemporadaNumeroRouteImport } from './routes/serie.$id_.temporada.$numero'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoCategoriaRoute = CatalogoCategoriaRouteImport.update({
  id: '/catalogo/$categoria',
  path: '/catalogo/$categoria',
  getParentRoute: () => rootRouteImport,
} as any)
const ColeccionIdRoute = ColeccionIdRouteImport.update({
  id: '/coleccion/$id',
  path: '/coleccion/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PeliculaIdRoute = PeliculaIdRouteImport.update({
  id: '/pelicula/$id',
  path: '/pelicula/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonaIdRoute = PersonaIdRouteImport.update({
  id: '/persona/$id',
  path: '/persona/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SerieIdRoute = SerieIdRouteImport.update({
  id: '/serie/$id',
  path: '/serie/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SerieIdTemporadaNumeroRoute = SerieIdTemporadaNumeroRouteImport.update({
  id: '/serie/$id_/temporada/$numero',
  path: '/serie/$id/temporada/$numero',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/favoritos': typeof FavoritosRoute
  '/catalogo/$categoria': typeof CatalogoCategoriaRoute
  '/coleccion/$id': typeof ColeccionIdRoute
  '/pelicula/$id': typeof PeliculaIdRoute
  '/persona/$id': typeof PersonaIdRoute
  '/serie/$id': typeof SerieIdRoute
  '/serie/$id/temporada/$numero': typeof SerieIdTemporadaNumeroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/favoritos': typeof FavoritosRoute
  '/catalogo/$categoria': typeof CatalogoCategoriaRoute
  '/coleccion/$id': typeof ColeccionIdRoute
  '/pelicula/$id': typeof PeliculaIdRoute
  '/persona/$id': typeof PersonaIdRoute
  '/serie/$id': typeof SerieIdRoute
  '/serie/$id/temporada/$numero': typeof SerieIdTemporadaNumeroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/favoritos': typeof FavoritosRoute
  '/catalogo/$categoria': typeof CatalogoCategoriaRoute
  '/coleccion/$id': typeof ColeccionIdRoute
  '/pelicula/$id': typeof PeliculaIdRoute
  '/persona/$id': typeof PersonaIdRoute
  '/serie/$id': typeof SerieIdRoute
  '/serie/$id_/temporada/$numero': typeof SerieIdTemporadaNumeroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buscar'
    | '/favoritos'
    | '/catalogo/$categoria'
    | '/coleccion/$id'
    | '/pelicula/$id'
    | '/persona/$id'
    | '/serie/$id'
    | '/serie/$id/temporada/$numero'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buscar'
    | '/favoritos'
    | '/catalogo/$categoria'
    | '/coleccion/$id'
    | '/pelicula/$id'
    | '/persona/$id'
    | '/serie/$id'
    | '/serie/$id/temporada/$numero'
  id:
    | '__root__'
    | '/'
    | '/buscar'
    | '/favoritos'
    | '/catalogo/$categoria'
    | '/coleccion/$id'
    | '/pelicula/$id'
    | '/persona/$id'
    | '/serie/$id'
    | '/serie/$id_/temporada/$numero'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuscarRoute: typeof BuscarRoute
  FavoritosRoute: typeof FavoritosRoute
  CatalogoCategoriaRoute: typeof CatalogoCategoriaRoute
  ColeccionIdRoute: typeof ColeccionIdRoute
  PeliculaIdRoute: typeof PeliculaIdRoute
  PersonaIdRoute: typeof PersonaIdRoute
  SerieIdRoute: typeof SerieIdRoute
  SerieIdTemporadaNumeroRoute: typeof SerieIdTemporadaNumeroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo/$categoria': {
      id: '/catalogo/$categoria'
      path: '/catalogo/$categoria'
      fullPath: '/catalogo/$categoria'
      preLoaderRoute: typeof CatalogoCategoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coleccion/$id': {
      id: '/coleccion/$id'
      path: '/coleccion/$id'
      fullPath: '/coleccion/$id'
      preLoaderRoute: typeof ColeccionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelicula/$id': {
      id: '/pelicula/$id'
      path: '/pelicula/$id'
      fullPath: '/pelicula/$id'
      preLoaderRoute: typeof PeliculaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persona/$id': {
      id: '/persona/$id'
      path: '/persona/$id'
      fullPath: '/persona/$id'
      preLoaderRoute: typeof PersonaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serie/$id': {
      id: '/serie/$id'
      path: '/serie/$id'
      fullPath: '/serie/$id'
      preLoaderRoute: typeof SerieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serie/$id_/temporada/$numero': {
      id: '/serie/$id_/temporada/$numero'
      path: '/serie/$id/temporada/$numero'
      fullPath: '/serie/$id/temporada/$numero'
      preLoaderRoute: typeof SerieIdTemporadaNumeroRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuscarRoute: BuscarRoute,
  FavoritosRoute: FavoritosRoute,
  CatalogoCategoriaRoute: CatalogoCategoriaRoute,
  ColeccionIdRoute: ColeccionIdRoute,
  PeliculaIdRoute: PeliculaIdRoute,
  PersonaIdRoute: PersonaIdRoute,
  SerieIdRoute: SerieIdRoute,
  SerieIdTemporadaNumeroRoute: SerieIdTemporadaNumeroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
